version: "3.8"
   
services:
    fastapi:
        build: .
        container_name: fastapi
        command: uvicorn main:app --reload
        volumes:
            - .:/usr/src/app/
        ports:
            - "8000:8000"
        environment:
            - DEBUG=1
            - FASTAPI_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - redis
    celery:
        build: .
        command: celery -A main.celery worker --loglevel=info
        volumes:
            - .:/usr/src/app
        environment:
            - DEBUG=1
            - FASTAPI_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - CELERY_BROKER=redis://redis:6379/0
        depends_on:
            - fastapi
            - redis 
    redis:
        image: "redis:alpine"